name: Terraform Destroy
on:
  workflow_dispatch

jobs:
  destroy:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Destroy Terraform
        run: |
          cd terraform
          terraform version
          terraform init -backend-config="bucket=$TF_STATE_BUCKET"
          terraform apply -destroy -auto-approve